package Swag.Absyn; // Java Package generated by the BNF Converter.

public class CmpOpEq extends ComparisonOp implements Swag.Visitable
{

  public CmpOpEq() { }

  public void accept(Swag.Visitor v) { v.visitCmpOpEq(this); }
}

