package Swag.Absyn; // Java Package generated by the BNF Converter.

public class CmpOpLeq extends ComparisonOp implements Swag.Visitable
{

  public CmpOpLeq() { }

  public void accept(Swag.Visitor v) { v.visitCmpOpLeq(this); }
}

