package Swag.Absyn; // Java Package generated by the BNF Converter.

public class CmpOpLt extends ComparisonOp implements Swag.Visitable
{

  public CmpOpLt() { }

  public void accept(Swag.Visitor v) { v.visitCmpOpLt(this); }
}

