package Swag.Absyn; // Java Package generated by the BNF Converter.

public class CmpOpGeq extends ComparisonOp implements Swag.Visitable
{

  public CmpOpGeq() { }

  public void accept(Swag.Visitor v) { v.visitCmpOpGeq(this); }
}

