package Swag.Absyn; // Java Package generated by the BNF Converter.

public class CmpOpGt extends ComparisonOp implements Swag.Visitable
{

  public CmpOpGt() { }

  public void accept(Swag.Visitor v) { v.visitCmpOpGt(this); }
}

