package Swag.Absyn; // Java Package generated by the BNF Converter.

public class ESet extends Exp implements Swag.Visitable
{
  public Set set_;

  public ESet(Set p1) { set_ = p1; }

  public void accept(Swag.Visitor v) { v.visitESet(this); }
}

