package Swag.Absyn; // Java Package generated by the BNF Converter.

public class LBottom extends Location implements Swag.Visitable
{

  public LBottom() { }

  public void accept(Swag.Visitor v) { v.visitLBottom(this); }
}

