package Swag.Absyn; // Java Package generated by the BNF Converter.

public class ListSet implements Swag.Visitable
{
  public Set set_;
  public ListSet listset_;

  public ListSet(Set p1, ListSet p2) { set_ = p1; listset_ = p2; }
  public ListSet reverse()
  {
    if (listset_ == null) return this;
    else
    {
      ListSet tmp = listset_.reverse(this);
      listset_ = null;
      return tmp;
    }
  }
  public ListSet reverse(ListSet prev)
  {
    if (listset_ == null)
    {
      listset_ = prev;
      return this;
    }
    else
    {
      ListSet tmp = listset_.reverse(this);
      listset_ = prev;
      return tmp;
    }
  }


  public void accept(Swag.Visitor v) { v.visitListSet(this); }
}
