package Swag.Absyn; // Java Package generated by the BNF Converter.

public class ListTournament implements Swag.Visitable
{
  public Tournament tournament_;
  public ListTournament listtournament_;

  public ListTournament(Tournament p1, ListTournament p2) { tournament_ = p1; listtournament_ = p2; }
  public ListTournament reverse()
  {
    if (listtournament_ == null) return this;
    else
    {
      ListTournament tmp = listtournament_.reverse(this);
      listtournament_ = null;
      return tmp;
    }
  }
  public ListTournament reverse(ListTournament prev)
  {
    if (listtournament_ == null)
    {
      listtournament_ = prev;
      return this;
    }
    else
    {
      ListTournament tmp = listtournament_.reverse(this);
      listtournament_ = prev;
      return tmp;
    }
  }


  public void accept(Swag.Visitor v) { v.visitListTournament(this); }
}
