package Swag.Absyn; // Java Package generated by the BNF Converter.

public class LTop extends Location implements Swag.Visitable
{

  public LTop() { }

  public void accept(Swag.Visitor v) { v.visitLTop(this); }
}

