package Swag.Absyn; // Java Package generated by the BNF Converter.

public class PFrac extends Part implements Swag.Visitable
{
  public Integer integer_1, integer_2;

  public PFrac(Integer p1, Integer p2) { integer_1 = p1; integer_2 = p2; }

  public void accept(Swag.Visitor v) { v.visitPFrac(this); }
}

