package Swag.Absyn; // Java Package generated by the BNF Converter.

public class PInt extends Part implements Swag.Visitable
{
  public Integer integer_;

  public PInt(Integer p1) { integer_ = p1; }

  public void accept(Swag.Visitor v) { v.visitPInt(this); }
}

