package Swag.Absyn; // Java Package generated by the BNF Converter.

public class Player  implements Swag.Visitable
{
  public String ident_;

  public Player(String p1) { ident_ = p1; }

  public void accept(Swag.Visitor v) { v.visitPlayer(this); }
}

