package Swag.Absyn; // Java Package generated by the BNF Converter.

public class Prog extends Program implements Swag.Visitable
{
  public ListTournament listtournament_;

  public Prog(ListTournament p1) { listtournament_ = p1; }

  public void accept(Swag.Visitor v) { v.visitProg(this); }
}

