package Swag.Absyn; // Java Package generated by the BNF Converter.

public class SAss extends Stmt implements Swag.Visitable
{
  public String ident_;
  public Exp exp_;

  public SAss(String p1, Exp p2) { ident_ = p1; exp_ = p2; }

  public void accept(Swag.Visitor v) { v.visitSAss(this); }
}

