package Swag.Absyn; // Java Package generated by the BNF Converter.

public class SAttrVal extends Set implements Swag.Visitable
{
  public StringComparison stringcomparison_;

  public SAttrVal(StringComparison p1) { stringcomparison_ = p1; }

  public void accept(Swag.Visitor v) { v.visitSAttrVal(this); }
}

