package Swag.Absyn; // Java Package generated by the BNF Converter.

public class SCmp extends StringComparison implements Swag.Visitable
{
  public String string_;
  public ComparisonOp comparisonop_;
  public SimpleExp simpleexp_;

  public SCmp(String p1, ComparisonOp p2, SimpleExp p3) { string_ = p1; comparisonop_ = p2; simpleexp_ = p3; }

  public void accept(Swag.Visitor v) { v.visitSCmp(this); }
}

