package Swag.Absyn; // Java Package generated by the BNF Converter.

public class SelTake extends Selection implements Swag.Visitable
{
  public Location location_;
  public Part part_;
  public Set set_;

  public SelTake(Location p1, Part p2, Set p3) { location_ = p1; part_ = p2; set_ = p3; }

  public void accept(Swag.Visitor v) { v.visitSelTake(this); }
}

