package Swag.Absyn; // Java Package generated by the BNF Converter.

public class SHasAttr extends Set implements Swag.Visitable
{
  public String string_;

  public SHasAttr(String p1) { string_ = p1; }

  public void accept(Swag.Visitor v) { v.visitSHasAttr(this); }
}

