package Swag.Absyn; // Java Package generated by the BNF Converter.

public class SimpExpStr extends SimpleExp implements Swag.Visitable
{
  public String string_;

  public SimpExpStr(String p1) { string_ = p1; }

  public void accept(Swag.Visitor v) { v.visitSimpExpStr(this); }
}

