package Swag.Absyn; // Java Package generated by the BNF Converter.

public class SimpExpInt extends SimpleExp implements Swag.Visitable
{
  public Integer integer_;

  public SimpExpInt(Integer p1) { integer_ = p1; }

  public void accept(Swag.Visitor v) { v.visitSimpExpInt(this); }
}

