package Swag.Absyn; // Java Package generated by the BNF Converter.

public class SNot extends Set implements Swag.Visitable
{
  public Set set_;

  public SNot(Set p1) { set_ = p1; }

  public void accept(Swag.Visitor v) { v.visitSNot(this); }
}

