package Swag.Absyn; // Java Package generated by the BNF Converter.

public class SSend extends Stmt implements Swag.Visitable
{
  public Set set_;
  public String ident_;

  public SSend(Set p1, String p2) { set_ = p1; ident_ = p2; }

  public void accept(Swag.Visitor v) { v.visitSSend(this); }
}

