package Swag.Absyn; // Java Package generated by the BNF Converter.

public class SUnion extends Set implements Swag.Visitable
{
  public ListSet listset_;

  public SUnion(ListSet p1) { listset_ = p1; }

  public void accept(Swag.Visitor v) { v.visitSUnion(this); }
}

