package Swag.Absyn; // Java Package generated by the BNF Converter.

public class SVar extends Set implements Swag.Visitable
{
  public String ident_;

  public SVar(String p1) { ident_ = p1; }

  public void accept(Swag.Visitor v) { v.visitSVar(this); }
}

