// This JLex file was machine-generated by the BNF converter
package Swag;
import java_cup.runtime.*;
import Swag.Absyn.*;


class Yylex implements java_cup.runtime.Scanner {
	private final int YY_BUFFER_SIZE = 512;
	private final int YY_F = -1;
	private final int YY_NO_STATE = -1;
	private final int YY_NOT_ACCEPT = 0;
	private final int YY_START = 1;
	private final int YY_END = 2;
	private final int YY_NO_ANCHOR = 4;
	private final int YY_BOL = 256;
	private final int YY_EOF = 257;

  String pstring = new String();
  public int line_num() { return (yyline+1); }
  public String buff() { return new String(yy_buffer,yy_buffer_index,10).trim(); }
	private java.io.BufferedReader yy_reader;
	private int yy_buffer_index;
	private int yy_buffer_read;
	private int yy_buffer_start;
	private int yy_buffer_end;
	private char yy_buffer[];
	private int yyline;
	private boolean yy_at_bol;
	private int yy_lexical_state;

	Yylex (java.io.Reader reader) {
		this ();
		if (null == reader) {
			throw (new Error("Error: Bad input stream initializer."));
		}
		yy_reader = new java.io.BufferedReader(reader);
	}

	Yylex (java.io.InputStream instream) {
		this ();
		if (null == instream) {
			throw (new Error("Error: Bad input stream initializer."));
		}
		yy_reader = new java.io.BufferedReader(new java.io.InputStreamReader(instream));
	}

	private Yylex () {
		yy_buffer = new char[YY_BUFFER_SIZE];
		yy_buffer_read = 0;
		yy_buffer_index = 0;
		yy_buffer_start = 0;
		yy_buffer_end = 0;
		yyline = 0;
		yy_at_bol = true;
		yy_lexical_state = YYINITIAL;
	}

	private boolean yy_eof_done = false;
	private final int STRING = 5;
	private final int ESCAPED = 6;
	private final int YYINITIAL = 0;
	private final int COMMENT = 1;
	private final int CHAREND = 4;
	private final int CHARESC = 3;
	private final int CHAR = 2;
	private final int yy_state_dtrans[] = {
		0,
		44,
		44,
		44,
		44,
		46,
		48
	};
	private void yybegin (int state) {
		yy_lexical_state = state;
	}
	private int yy_advance ()
		throws java.io.IOException {
		int next_read;
		int i;
		int j;

		if (yy_buffer_index < yy_buffer_read) {
			return yy_buffer[yy_buffer_index++];
		}

		if (0 != yy_buffer_start) {
			i = yy_buffer_start;
			j = 0;
			while (i < yy_buffer_read) {
				yy_buffer[j] = yy_buffer[i];
				++i;
				++j;
			}
			yy_buffer_end = yy_buffer_end - yy_buffer_start;
			yy_buffer_start = 0;
			yy_buffer_read = j;
			yy_buffer_index = j;
			next_read = yy_reader.read(yy_buffer,
					yy_buffer_read,
					yy_buffer.length - yy_buffer_read);
			if (-1 == next_read) {
				return YY_EOF;
			}
			yy_buffer_read = yy_buffer_read + next_read;
		}

		while (yy_buffer_index >= yy_buffer_read) {
			if (yy_buffer_index >= yy_buffer.length) {
				yy_buffer = yy_double(yy_buffer);
			}
			next_read = yy_reader.read(yy_buffer,
					yy_buffer_read,
					yy_buffer.length - yy_buffer_read);
			if (-1 == next_read) {
				return YY_EOF;
			}
			yy_buffer_read = yy_buffer_read + next_read;
		}
		return yy_buffer[yy_buffer_index++];
	}
	private void yy_move_end () {
		if (yy_buffer_end > yy_buffer_start &&
		    '\n' == yy_buffer[yy_buffer_end-1])
			yy_buffer_end--;
		if (yy_buffer_end > yy_buffer_start &&
		    '\r' == yy_buffer[yy_buffer_end-1])
			yy_buffer_end--;
	}
	private boolean yy_last_was_cr=false;
	private void yy_mark_start () {
		int i;
		for (i = yy_buffer_start; i < yy_buffer_index; ++i) {
			if ('\n' == yy_buffer[i] && !yy_last_was_cr) {
				++yyline;
			}
			if ('\r' == yy_buffer[i]) {
				++yyline;
				yy_last_was_cr=true;
			} else yy_last_was_cr=false;
		}
		yy_buffer_start = yy_buffer_index;
	}
	private void yy_mark_end () {
		yy_buffer_end = yy_buffer_index;
	}
	private void yy_to_mark () {
		yy_buffer_index = yy_buffer_end;
		yy_at_bol = (yy_buffer_end > yy_buffer_start) &&
		            ('\r' == yy_buffer[yy_buffer_end-1] ||
		             '\n' == yy_buffer[yy_buffer_end-1] ||
		             2028/*LS*/ == yy_buffer[yy_buffer_end-1] ||
		             2029/*PS*/ == yy_buffer[yy_buffer_end-1]);
	}
	private java.lang.String yytext () {
		return (new java.lang.String(yy_buffer,
			yy_buffer_start,
			yy_buffer_end - yy_buffer_start));
	}
	private int yylength () {
		return yy_buffer_end - yy_buffer_start;
	}
	private char[] yy_double (char buf[]) {
		int i;
		char newbuf[];
		newbuf = new char[2*buf.length];
		for (i = 0; i < buf.length; ++i) {
			newbuf[i] = buf[i];
		}
		return newbuf;
	}
	private final int YY_E_INTERNAL = 0;
	private final int YY_E_MATCH = 1;
	private java.lang.String yy_error_string[] = {
		"Error: Internal error.\n",
		"Error: Unmatched input.\n"
	};
	private void yy_error (int code,boolean fatal) {
		java.lang.System.out.print(yy_error_string[code]);
		java.lang.System.out.flush();
		if (fatal) {
			throw new Error("Fatal Error.\n");
		}
	}
	private int[][] unpackFromString(int size1, int size2, String st) {
		int colonIndex = -1;
		String lengthString;
		int sequenceLength = 0;
		int sequenceInteger = 0;

		int commaIndex;
		String workString;

		int res[][] = new int[size1][size2];
		for (int i= 0; i < size1; i++) {
			for (int j= 0; j < size2; j++) {
				if (sequenceLength != 0) {
					res[i][j] = sequenceInteger;
					sequenceLength--;
					continue;
				}
				commaIndex = st.indexOf(',');
				workString = (commaIndex==-1) ? st :
					st.substring(0, commaIndex);
				st = st.substring(commaIndex+1);
				colonIndex = workString.indexOf(':');
				if (colonIndex == -1) {
					res[i][j]=Integer.parseInt(workString);
					continue;
				}
				lengthString =
					workString.substring(colonIndex+1);
				sequenceLength=Integer.parseInt(lengthString);
				workString=workString.substring(0,colonIndex);
				sequenceInteger=Integer.parseInt(workString);
				res[i][j] = sequenceInteger;
				sequenceLength--;
			}
		}
		return res;
	}
	private int yy_acpt[] = {
		/* 0 */ YY_NOT_ACCEPT,
		/* 1 */ YY_NO_ANCHOR,
		/* 2 */ YY_NO_ANCHOR,
		/* 3 */ YY_NO_ANCHOR,
		/* 4 */ YY_NO_ANCHOR,
		/* 5 */ YY_NO_ANCHOR,
		/* 6 */ YY_NO_ANCHOR,
		/* 7 */ YY_NO_ANCHOR,
		/* 8 */ YY_NO_ANCHOR,
		/* 9 */ YY_NO_ANCHOR,
		/* 10 */ YY_NO_ANCHOR,
		/* 11 */ YY_NO_ANCHOR,
		/* 12 */ YY_NO_ANCHOR,
		/* 13 */ YY_NO_ANCHOR,
		/* 14 */ YY_NO_ANCHOR,
		/* 15 */ YY_NO_ANCHOR,
		/* 16 */ YY_NO_ANCHOR,
		/* 17 */ YY_NO_ANCHOR,
		/* 18 */ YY_NO_ANCHOR,
		/* 19 */ YY_NO_ANCHOR,
		/* 20 */ YY_NO_ANCHOR,
		/* 21 */ YY_NO_ANCHOR,
		/* 22 */ YY_NO_ANCHOR,
		/* 23 */ YY_NO_ANCHOR,
		/* 24 */ YY_NO_ANCHOR,
		/* 25 */ YY_NO_ANCHOR,
		/* 26 */ YY_NO_ANCHOR,
		/* 27 */ YY_NO_ANCHOR,
		/* 28 */ YY_NO_ANCHOR,
		/* 29 */ YY_NO_ANCHOR,
		/* 30 */ YY_NO_ANCHOR,
		/* 31 */ YY_NO_ANCHOR,
		/* 32 */ YY_NO_ANCHOR,
		/* 33 */ YY_NO_ANCHOR,
		/* 34 */ YY_NO_ANCHOR,
		/* 35 */ YY_NO_ANCHOR,
		/* 36 */ YY_NO_ANCHOR,
		/* 37 */ YY_NO_ANCHOR,
		/* 38 */ YY_NO_ANCHOR,
		/* 39 */ YY_NO_ANCHOR,
		/* 40 */ YY_NO_ANCHOR,
		/* 41 */ YY_NO_ANCHOR,
		/* 42 */ YY_NOT_ACCEPT,
		/* 43 */ YY_NO_ANCHOR,
		/* 44 */ YY_NOT_ACCEPT,
		/* 45 */ YY_NO_ANCHOR,
		/* 46 */ YY_NOT_ACCEPT,
		/* 47 */ YY_NO_ANCHOR,
		/* 48 */ YY_NOT_ACCEPT,
		/* 49 */ YY_NO_ANCHOR,
		/* 50 */ YY_NO_ANCHOR,
		/* 51 */ YY_NO_ANCHOR,
		/* 52 */ YY_NO_ANCHOR,
		/* 53 */ YY_NO_ANCHOR,
		/* 54 */ YY_NO_ANCHOR,
		/* 55 */ YY_NO_ANCHOR,
		/* 56 */ YY_NO_ANCHOR,
		/* 57 */ YY_NO_ANCHOR,
		/* 58 */ YY_NO_ANCHOR,
		/* 59 */ YY_NO_ANCHOR,
		/* 60 */ YY_NO_ANCHOR,
		/* 61 */ YY_NO_ANCHOR,
		/* 62 */ YY_NO_ANCHOR,
		/* 63 */ YY_NO_ANCHOR,
		/* 64 */ YY_NO_ANCHOR,
		/* 65 */ YY_NO_ANCHOR,
		/* 66 */ YY_NO_ANCHOR,
		/* 67 */ YY_NO_ANCHOR,
		/* 68 */ YY_NO_ANCHOR,
		/* 69 */ YY_NO_ANCHOR,
		/* 70 */ YY_NO_ANCHOR,
		/* 71 */ YY_NO_ANCHOR,
		/* 72 */ YY_NO_ANCHOR,
		/* 73 */ YY_NO_ANCHOR,
		/* 74 */ YY_NO_ANCHOR,
		/* 75 */ YY_NO_ANCHOR,
		/* 76 */ YY_NO_ANCHOR
	};
	private int yy_cmap[] = unpackFromString(1,258,
"37:9,42,34,37,42,33,37:18,42,37,35,37:2,13,37,41,10,11,37,5,12,37:2,14,38:1" +
"0,37,3,8,4,9,37:2,39:26,6,36,7,37,41,37,28,15,25,27,23,19,40,32,21,40,29,40" +
",18,22,16,30,40,20,24,17,26,40,31,40:3,1,37,2,37:66,39:23,37,39:7,40:24,37," +
"40:8,0:2")[0];

	private int yy_rmap[] = unpackFromString(1,77,
"0,1:8,2,3,1:4,4,5,1:2,6,1:2,7,8,1,9:9,1:8,10,11,12,13,14,15,16,17,18,19,20," +
"21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,9,40,41,42,9")[0];

	private int yy_nxt[][] = unpackFromString(43,43,
"1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,76,43,70,64,76,45,56,76,65,76:6,66,7" +
"6,17:2,18,-1:2,19,76:2,-1,17,-1:47,20,-1:42,21,-1:52,42,-1:43,76,71,76:16,-" +
"1:5,72:2,76,72,-1:39,19,-1:19,76:15,25,76:2,-1:5,72:2,76,72,-1:16,76:2,73,7" +
"6:15,-1:5,72:2,76,72,-1:16,76:18,-1:5,72:2,76,72,-1:2,42:33,24,42:8,-1:15,7" +
"6,22,76:11,57,76:4,-1:5,72:2,76,72,-1,1,-1:57,76:7,23,76:10,-1:5,72:2,76,72" +
",-1,1,34:32,-1:2,35,36,34:6,-1:15,76:2,26,76:15,-1:5,72:2,76,72,-1,1,37:16," +
"38,37:4,39,37:10,-1:2,40,41,37:6,-1:15,76:8,27,76:9,-1:5,72:2,76,72,-1:16,7" +
"6:3,28,76:14,-1:5,72:2,76,72,-1:16,76:12,29,76:5,-1:5,72:2,76,72,-1:16,76:1" +
"7,30,-1:5,72:2,76,72,-1:16,76:9,31,76:8,-1:5,72:2,76,72,-1:16,76:3,32,76:14" +
",-1:5,72:2,76,72,-1:16,76:2,33,76:15,-1:5,72:2,76,72,-1:16,76,47,76:16,-1:5" +
",72:2,76,72,-1:16,76:14,49,76:3,-1:5,72:2,76,72,-1:16,76,50,76:16,-1:5,72:2" +
",76,72,-1:16,76:7,51,76:10,-1:5,72:2,76,72,-1:16,76:2,52,76:15,-1:5,72:2,76" +
",72,-1:16,76:11,53,76:6,-1:5,72:2,76,72,-1:16,76,54,76:16,-1:5,72:2,76,72,-" +
"1:16,76:10,55,76:7,-1:5,72:2,76,72,-1:16,76:5,58,76:12,-1:5,72:2,76,72,-1:1" +
"6,76:8,59,76:9,-1:5,72:2,76,72,-1:16,76:6,60,76:11,-1:5,72:2,76,72,-1:16,76" +
":7,61,76:10,-1:5,72:2,76,72,-1:16,76:2,62,76:15,-1:5,72:2,76,72,-1:16,76:8," +
"63,76:9,-1:5,72:2,76,72,-1:16,76:6,67,76:11,-1:5,72:2,76,72,-1:16,76:2,68,7" +
"6:15,-1:5,72:2,76,72,-1:16,76:8,74,76:9,-1:5,72:2,76,72,-1:16,76:5,75,76:12" +
",-1:5,72:2,76,72,-1:16,76:9,69,76:8,-1:5,72:2,76,72,-1");

	public java_cup.runtime.Symbol next_token ()
		throws java.io.IOException {
		int yy_lookahead;
		int yy_anchor = YY_NO_ANCHOR;
		int yy_state = yy_state_dtrans[yy_lexical_state];
		int yy_next_state = YY_NO_STATE;
		int yy_last_accept_state = YY_NO_STATE;
		boolean yy_initial = true;
		int yy_this_accept;

		yy_mark_start();
		yy_this_accept = yy_acpt[yy_state];
		if (YY_NOT_ACCEPT != yy_this_accept) {
			yy_last_accept_state = yy_state;
			yy_mark_end();
		}
		while (true) {
			if (yy_initial && yy_at_bol) yy_lookahead = YY_BOL;
			else yy_lookahead = yy_advance();
			yy_next_state = YY_F;
			yy_next_state = yy_nxt[yy_rmap[yy_state]][yy_cmap[yy_lookahead]];
			if (YY_EOF == yy_lookahead && true == yy_initial) {
				return null;
			}
			if (YY_F != yy_next_state) {
				yy_state = yy_next_state;
				yy_initial = false;
				yy_this_accept = yy_acpt[yy_state];
				if (YY_NOT_ACCEPT != yy_this_accept) {
					yy_last_accept_state = yy_state;
					yy_mark_end();
				}
			}
			else {
				if (YY_NO_STATE == yy_last_accept_state) {
					throw (new Error("Lexical Error: Unmatched Input."));
				}
				else {
					yy_anchor = yy_acpt[yy_last_accept_state];
					if (0 != (YY_END & yy_anchor)) {
						yy_move_end();
					}
					yy_to_mark();
					switch (yy_last_accept_state) {
					case 1:
						
					case -2:
						break;
					case 2:
						{ return new Symbol(sym._SYMB_0); }
					case -3:
						break;
					case 3:
						{ return new Symbol(sym._SYMB_1); }
					case -4:
						break;
					case 4:
						{ return new Symbol(sym._SYMB_2); }
					case -5:
						break;
					case 5:
						{ return new Symbol(sym._SYMB_3); }
					case -6:
						break;
					case 6:
						{ return new Symbol(sym._SYMB_4); }
					case -7:
						break;
					case 7:
						{ return new Symbol(sym._SYMB_5); }
					case -8:
						break;
					case 8:
						{ return new Symbol(sym._SYMB_6); }
					case -9:
						break;
					case 9:
						{ return new Symbol(sym._SYMB_7); }
					case -10:
						break;
					case 10:
						{ return new Symbol(sym._SYMB_8); }
					case -11:
						break;
					case 11:
						{ return new Symbol(sym._SYMB_11); }
					case -12:
						break;
					case 12:
						{ return new Symbol(sym._SYMB_12); }
					case -13:
						break;
					case 13:
						{ return new Symbol(sym._SYMB_13); }
					case -14:
						break;
					case 14:
						{ return new Symbol(sym._SYMB_14); }
					case -15:
						break;
					case 15:
						{ return new Symbol(sym._SYMB_15); }
					case -16:
						break;
					case 16:
						{ return new Symbol(sym._IDENT_, new String(yytext())); }
					case -17:
						break;
					case 17:
						{ /* ignore white space. */ }
					case -18:
						break;
					case 18:
						{ yybegin(STRING); }
					case -19:
						break;
					case 19:
						{ return new Symbol(sym._INTEGER_, new Integer(yytext())); }
					case -20:
						break;
					case 20:
						{ return new Symbol(sym._SYMB_9); }
					case -21:
						break;
					case 21:
						{ return new Symbol(sym._SYMB_10); }
					case -22:
						break;
					case 22:
						{ return new Symbol(sym._SYMB_24); }
					case -23:
						break;
					case 23:
						{ return new Symbol(sym._SYMB_18); }
					case -24:
						break;
					case 24:
						{ /* BNFC single-line comment */ }
					case -25:
						break;
					case 25:
						{ return new Symbol(sym._SYMB_25); }
					case -26:
						break;
					case 26:
						{ return new Symbol(sym._SYMB_21); }
					case -27:
						break;
					case 27:
						{ return new Symbol(sym._SYMB_23); }
					case -28:
						break;
					case 28:
						{ return new Symbol(sym._SYMB_17); }
					case -29:
						break;
					case 29:
						{ return new Symbol(sym._SYMB_22); }
					case -30:
						break;
					case 30:
						{ return new Symbol(sym._SYMB_26); }
					case -31:
						break;
					case 31:
						{ return new Symbol(sym._SYMB_20); }
					case -32:
						break;
					case 32:
						{ return new Symbol(sym._SYMB_16); }
					case -33:
						break;
					case 33:
						{ return new Symbol(sym._SYMB_19); }
					case -34:
						break;
					case 34:
						{ pstring += yytext(); }
					case -35:
						break;
					case 35:
						{ String foo = pstring; pstring = new String(); yybegin(YYINITIAL); return new Symbol(sym._STRING_, foo); }
					case -36:
						break;
					case 36:
						{ yybegin(ESCAPED); }
					case -37:
						break;
					case 37:
						{ pstring += yytext(); yybegin(STRING); }
					case -38:
						break;
					case 38:
						{ pstring += "\t"; yybegin(STRING); }
					case -39:
						break;
					case 39:
						{ pstring +=  "\n"; yybegin(STRING); }
					case -40:
						break;
					case 40:
						{ pstring += "\""; yybegin(STRING); }
					case -41:
						break;
					case 41:
						{ pstring += "\\"; yybegin(STRING); }
					case -42:
						break;
					case 43:
						{ return new Symbol(sym._IDENT_, new String(yytext())); }
					case -43:
						break;
					case 45:
						{ return new Symbol(sym._IDENT_, new String(yytext())); }
					case -44:
						break;
					case 47:
						{ return new Symbol(sym._IDENT_, new String(yytext())); }
					case -45:
						break;
					case 49:
						{ return new Symbol(sym._IDENT_, new String(yytext())); }
					case -46:
						break;
					case 50:
						{ return new Symbol(sym._IDENT_, new String(yytext())); }
					case -47:
						break;
					case 51:
						{ return new Symbol(sym._IDENT_, new String(yytext())); }
					case -48:
						break;
					case 52:
						{ return new Symbol(sym._IDENT_, new String(yytext())); }
					case -49:
						break;
					case 53:
						{ return new Symbol(sym._IDENT_, new String(yytext())); }
					case -50:
						break;
					case 54:
						{ return new Symbol(sym._IDENT_, new String(yytext())); }
					case -51:
						break;
					case 55:
						{ return new Symbol(sym._IDENT_, new String(yytext())); }
					case -52:
						break;
					case 56:
						{ return new Symbol(sym._IDENT_, new String(yytext())); }
					case -53:
						break;
					case 57:
						{ return new Symbol(sym._IDENT_, new String(yytext())); }
					case -54:
						break;
					case 58:
						{ return new Symbol(sym._IDENT_, new String(yytext())); }
					case -55:
						break;
					case 59:
						{ return new Symbol(sym._IDENT_, new String(yytext())); }
					case -56:
						break;
					case 60:
						{ return new Symbol(sym._IDENT_, new String(yytext())); }
					case -57:
						break;
					case 61:
						{ return new Symbol(sym._IDENT_, new String(yytext())); }
					case -58:
						break;
					case 62:
						{ return new Symbol(sym._IDENT_, new String(yytext())); }
					case -59:
						break;
					case 63:
						{ return new Symbol(sym._IDENT_, new String(yytext())); }
					case -60:
						break;
					case 64:
						{ return new Symbol(sym._IDENT_, new String(yytext())); }
					case -61:
						break;
					case 65:
						{ return new Symbol(sym._IDENT_, new String(yytext())); }
					case -62:
						break;
					case 66:
						{ return new Symbol(sym._IDENT_, new String(yytext())); }
					case -63:
						break;
					case 67:
						{ return new Symbol(sym._IDENT_, new String(yytext())); }
					case -64:
						break;
					case 68:
						{ return new Symbol(sym._IDENT_, new String(yytext())); }
					case -65:
						break;
					case 69:
						{ return new Symbol(sym._IDENT_, new String(yytext())); }
					case -66:
						break;
					case 70:
						{ return new Symbol(sym._IDENT_, new String(yytext())); }
					case -67:
						break;
					case 71:
						{ return new Symbol(sym._IDENT_, new String(yytext())); }
					case -68:
						break;
					case 72:
						{ return new Symbol(sym._IDENT_, new String(yytext())); }
					case -69:
						break;
					case 73:
						{ return new Symbol(sym._IDENT_, new String(yytext())); }
					case -70:
						break;
					case 74:
						{ return new Symbol(sym._IDENT_, new String(yytext())); }
					case -71:
						break;
					case 75:
						{ return new Symbol(sym._IDENT_, new String(yytext())); }
					case -72:
						break;
					case 76:
						{ return new Symbol(sym._IDENT_, new String(yytext())); }
					case -73:
						break;
					default:
						yy_error(YY_E_INTERNAL,false);
					case -1:
					}
					yy_initial = true;
					yy_state = yy_state_dtrans[yy_lexical_state];
					yy_next_state = YY_NO_STATE;
					yy_last_accept_state = YY_NO_STATE;
					yy_mark_start();
					yy_this_accept = yy_acpt[yy_state];
					if (YY_NOT_ACCEPT != yy_this_accept) {
						yy_last_accept_state = yy_state;
						yy_mark_end();
					}
				}
			}
		}
	}
}
